# Generated by Django 5.2.17 on 2026-09-12 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('province_city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('bus_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bus_type', models.CharField(choices=[('SEATER', 'Seater'), ('SLEEPER', 'Sleeper'), ('LIMOUSINE', 'Limousine')], max_length=20)),
                ('seat_capacity', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'buses',
                'constraints': [models.CheckConstraint(condition=models.Q(('seat_capacity__gt', 0)), name='chk_buses_capacity')],
            },
        ),
        migrations.CreateModel(
            name='BusSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(choices=[('STANDARD', 'Standard'), ('VIP', 'VIP')], default='STANDARD', max_length=20)),
                ('floor_number', models.PositiveSmallIntegerField(default=1)),
                ('seat_row', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('column_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='operations.bus')),
            ],
            options={
                'db_table': 'bus_seats',
                'indexes': [models.Index(fields=['bus', 'is_active'], name='idx_bus_seats_bus_active')],
                'constraints': [models.UniqueConstraint(fields=('bus', 'seat_number'), name='uq_bus_seat_number'), models.CheckConstraint(condition=models.Q(('floor_number__gte', 1)), name='chk_bus_seats_floor')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_code', models.CharField(max_length=20, unique=True)),
                ('route_name', models.CharField(max_length=160)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='destination_routes', to='operations.station')),
                ('origin_station', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='origin_routes', to='operations.station')),
            ],
            options={
                'db_table': 'routes',
                'indexes': [models.Index(fields=['origin_station', 'destination_station', 'status'], name='idx_routes_origin_dest')],
                'constraints': [models.CheckConstraint(condition=models.Q(('origin_station', models.F('destination_station')), _negated=True), name='chk_routes_different_stations'), models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='chk_routes_base_price')],
            },
        ),
    ]
