# Generated by Django 5.2.17 on 2026-09-07 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('bus_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bus_type', models.CharField(choices=[('SEATER', 'SEATER'), ('SLEEPER', 'SLEEPER'), ('LIMOUSINE', 'LIMOUSINE')], max_length=20)),
                ('seat_capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('MAINTENANCE', 'MAINTENANCE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'buses',
            },
        ),
    ]
