# Generated by Django 5.2.17 on 2026-09-12 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('operations', '0001_initial_operations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_code', models.CharField(max_length=30, unique=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN_FOR_BOOKING', 'Open for booking'), ('BOARDING', 'Boarding'), ('DEPARTED', 'Departed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN_FOR_BOOKING', max_length=30)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='operations.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='operations.route')),
            ],
            options={
                'db_table': 'trips',
            },
        ),
        migrations.CreateModel(
            name='TripStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_role', models.CharField(choices=[('DRIVER', 'Driver'), ('BUS_ATTENDANT', 'Bus Attendant')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trip_assignments', to='accounts.employee')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='operations.trip')),
            ],
            options={
                'db_table': 'trip_staff_assignments',
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['route', 'departure_time', 'status'], name='idx_trips_search'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['bus', 'departure_time', 'arrival_time', 'status'], name='idx_trips_bus_sched'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('arrival_time__gt', models.F('departure_time'))), name='chk_trips_time'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('ticket_price__gte', 0)), name='chk_trips_price'),
        ),
        migrations.AddIndex(
            model_name='tripstaffassignment',
            index=models.Index(fields=['employee', 'trip'], name='idx_trip_staff_employee'),
        ),
        migrations.AddConstraint(
            model_name='tripstaffassignment',
            constraint=models.UniqueConstraint(fields=('trip', 'employee'), name='uq_trip_employee'),
        ),
    ]
