# Generated by Django 5.2.17 on 2026-09-12 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0002_add_trips_and_assignments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(max_length=30, unique=True)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('booking_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='operations.trip')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=30, unique=True)),
                ('passenger_name', models.CharField(max_length=120)),
                ('passenger_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ticket_status', models.CharField(choices=[('HELD', 'Held'), ('CONFIRMED', 'Confirmed'), ('USED', 'Used'), ('CANCELLED', 'Cancelled')], default='HELD', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.booking')),
                ('bus_seat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='operations.busseat')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='operations.trip')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer_user', 'created_at'], name='idx_bkg_cust_created'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['trip', 'booking_status'], name='idx_bkg_trip_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_status', 'expires_at'], name='idx_bkg_expiry'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='chk_bookings_total'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['booking', 'ticket_status'], name='idx_tkt_booking_status'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['trip', 'ticket_status'], name='idx_tkt_trip_status'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('fare__gte', 0)), name='chk_tickets_fare'),
        ),
    ]
